---

- hosts: all
  become: true
  ignore_errors: yes
  tasks:

    - name: List available files
      shell: ls -la
      register: shell_result


    - debug:
        var: shell_result.stdout_lines


    - name: Get the MAC address
      debug: msg="{{ hostvars[inventory_hostname] }}"
    

    - name: Use the mac address to set interfaces bitch
      debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
    

    - name: Configure consistence interfaces
      shell: |
        echo "SUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"{{ hostvars[inventory_hostname].ansible_eth1.macaddress }}\", ATTR{dev_id}==\"0x0\", ATTR{type}==\"1\", NAME=\"eth_service\"
        SUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"{{ hostvars[inventory_hostname].ansible_wlan1.macaddress }}\", ATTR{dev_id}==\"0x0\", ATTR{type}==\"1\", NAME=\"wlan0\"" > /etc/udev/rules.d/70-persistent-net.rules
      register: shell2_result


    - debug:
        var: shell2_result.stdout_lines


    - name: Remove Raspberry Pi WiFi interface
      shell: |
        echo "blacklist brcmfmac
        blacklist brcmutil" > /etc/modprobe.d/raspi-blacklist.conf
      register: shell_result


    - name: Create a login user
      user:
        name: plume
        password: '$6$v7/89Jsz$7NIINXdB11MX8xObWRlmPzCSLQJ6U3Za4EREx8ghyMhb2Hrk3j9fBMyIzwzbBdPMIt0yKDxa3oglBS2rOVD3b/'
        groups: sudo, plume
        state: present
        system: yes


    - name: Plume configs
      shell: |
        echo 'plume ALL=(ALL) NOPASSWD: ALL' | sudo tee /etc/sudoers.d/plume > /dev/null
        sudo chmod 0400 /etc/sudoers.d/plume
        echo "" | sudo tee -a /etc/profile > /dev/null
        echo "### Localisation" | sudo tee -a /etc/profile > /dev/null
        echo "export LANGUAGE=C" | sudo tee -a /etc/profile > /dev/null
        echo "export LC_ALL=C" | sudo tee -a /etc/profile > /dev/null
        sudo mkdir -p /home/plume/.ssh
        sudo chmod 700 /home/plume/.ssh
        sudo touch /home/plume/.ssh/authorized_keys
        sudo chmod 664 /home/plume/.ssh/authorized_keys
        sudo chown -R plume.plume /home/plume/.ssh


    - name: Reboot a slow machine that might have lots of updates to apply
      reboot:
    
      
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: true


    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
      become: true


    - name: Apt get install many things
      apt:
        name: 
          - iperf
          - iperf3
          - expect
          - speedtest-cli
          - miniupnpc
          - dnsutils
          - vim
          - bridge-utils
          - build-essential
          - dos2unix
          - fakeroot
          - nmap
          - sshpass 
          - traceroute
          - zip
          - unzip
          - wireless-tools
          - wpasupplicant
          - vlan
          - python-pexpect
        state: present
        update_cache: true
      become: true


    - name: Plume configs
      become: true
      become_user: root
      shell: |
        sudo update-alternatives --set editor /usr/bin/vim.tiny
        echo "syntax on
        set ignorecase
        set ruler
        set mouse=n" > /home/plume/.vimrc
        sudo touch /root/.vimrc
        echo "os=rpi" | sudo tee /tb.conf > /dev/null
        echo "wifi=802.11n" | sudo tee -a /tb.conf > /dev/null
        echo "mimo=2x2" | sudo tee -a /tb.conf > /dev/null
        echo "" | sudo tee -a /tb.conf > /dev/null 
        echo "WIFI_MON_IF=wlan0" | sudo tee /tbvars.conf > /dev/null
        echo "WIFI_IF=wlan0" | sudo tee -a /tbvars.conf > /dev/null
        echo "" | sudo tee -a /tbvars.conf > /dev/null
        echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
        update_config=1
        country=SI
        
        network={
                ssid=\"ref-pi\"
                psk=\"welcome8\"
                proto=RSN
                key_mgmt=WPA-PSK
                scan_ssid=1
                priority=1
                # bssid=34:7a:60:2f:47:03
        }"
        

