---

- hosts: all
  become: true
  tasks:

    - name: List available files
      shell: ls -la
      register: shell_result


    - debug:
        var: shell_result.stdout_lines


    - name: Get the MAC address
      debug: msg="{{ hostvars[inventory_hostname] }}"
    

    - name: Use the mac address to set interfaces bitch
      debug: msg="{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"
    

    - name: Configure consistence interfaces
      shell: |
        echo "SUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"{{ hostvars[inventory_hostname].ansible_eth1.macaddress }}\", ATTR{dev_id}==\"0x0\", ATTR{type}==\"1\", NAME=\"eth_service\"
        SUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"{{ hostvars[inventory_hostname].ansible_wlan1.macaddress }}\", ATTR{dev_id}==\"0x0\", ATTR{type}==\"1\", NAME=\"wlan0\"" > /etc/udev/rules.d/70-persistent-net.rules
      register: shell2_result


    - debug:
        var: shell2_result.stdout_lines


    - name: Remove Raspberry Pi WiFi interface
      shell: |
        echo "blacklist brcmfmac
        blacklist brcmutil" > /etc/modprobe.d/raspi-blacklist.conf
      register: shell_result


    - name: Reboot
      shell: |
        reboot
#        sudo adduser plume
#        sudo usermod -a -G sudo plume
#        echo 'plume ALL=(ALL) NOPASSWD: ALL' | sudo tee /etc/sudoers.d/plume > /dev/null
#        sudo chmod 0400 /etc/sudoers.d/plume
#        echo "" | sudo tee -a /etc/profile > /dev/null
#        echo "### Localisation" | sudo tee -a /etc/profile > /dev/null
#        echo "export LANGUAGE=C" | sudo tee -a /etc/profile > /dev/null
#        echo "export LC_ALL=C" | sudo tee -a /etc/profile > /dev/null
#        sudo mkdir -p /home/plume/.ssh
#        sudo chmod 700 /home/plume/.ssh
#        sudo touch /home/plume/.ssh/authorized_keys
#        sudo chmod 664 /home/plume/.ssh/authorized_keys
#        sudo chown -R plume.plume /home/plume/.ssh

